const logo='assets/sansfx-logo.jpeg';
const demoMembers=[
 {name:'Ahmad F.',ib:'SANS Main',broker:'HFM',type:'Premium',status:'Active',lot:18.4},
 {name:'Rizky A.',ib:'IB Andi',broker:'Windsor',type:'Standard',status:'Active',lot:12.7},
 {name:'Dimas P.',ib:'IB Andi',broker:'HFM',type:'Cent',status:'KYC',lot:4.1},
 {name:'Nadia R.',ib:'IB Budi',broker:'Windsor',type:'Standard',status:'Inactive',lot:7.2},
];
let state={role:'owner',tab:'overview'};
function money(n){return '$'+Number(n).toLocaleString('en-US',{maximumFractionDigits:2})}
function home(){return `<div class="shell"><header class="topbar"><nav class="nav"><a class="brand" href="#/"><img src="${logo}"><span>SANS.<b>FX</b> HUB</span></a><div class="navlinks"><a href="#features">Fitur</a><a href="#community">Community</a><a href="#/bio/andi">Contoh Bio IB</a></div><a class="btn btn-gold" href="#/dashboard">Demo Dashboard</a></nav></header>
<main><section class="hero"><div><span class="eyebrow">COMMUNITY • IB • TRADING TOOLS</span><h1 class="grad">Satu Hub untuk membangun jaringan SANS.FX.</h1><p class="lead">Kelola member, Sub-IB, referral, performa trading, dan komunitas dari satu platform yang siap dipasang di bio TikTok.</p><div class="actions"><a class="btn btn-gold" href="#/join">Join SANS.FX</a><a class="btn btn-dark" href="#/dashboard">Lihat Dashboard</a><a class="btn btn-dark" href="#/bio/andi">Bio Sub-IB</a></div></div><div class="hero-card"><img src="${logo}"><div class="mini-grid"><div class="mini"><b>1 Hub</b><span>Community</span></div><div class="mini"><b>3 Role</b><span>Owner · IB · Member</span></div><div class="mini"><b>24/7</b><span>Online Access</span></div></div></div></section>
<section id="features" class="section"><h2>Core SANS.FX HUB</h2><div class="section-sub">Versi awal difokuskan ke fungsi yang langsung membantu operasional dan pertumbuhan.</div><div class="grid3"><div class="card"><div class="icon">◈</div><h3>IB Network</h3><p>Database Sub-IB, referral, client, lot, komisi dan bonus dalam satu sistem.</p></div><div class="card"><div class="icon">↗</div><h3>Bio Sub-IB</h3><p>Setiap Sub-IB memiliki landing page sendiri untuk TikTok bio, WhatsApp, Telegram dan referral broker.</p></div><div class="card"><div class="icon">％</div><h3>Performance Tracker</h3><p>Member menghitung growth, return, profit/loss, win rate dan perkembangan bulanan.</p></div></div></section>
<section id="community" class="section"><div class="card" style="text-align:center;padding:38px"><span class="eyebrow">TRADE • LEARN • GROW</span><h2 style="margin-top:16px">Bergabung dengan SANS.FX</h2><p class="section-sub">Community, education, trading tools dan jaringan IB dalam satu ekosistem.</p><div class="actions" style="justify-content:center"><a href="#/join" class="btn btn-gold">Daftar Member</a><a href="#/bio/andi" class="btn btn-dark">Lihat Halaman IB</a></div></div></section></main><div class="footer">© SANS.FX — Community & IB Management Platform</div></div>`}
function sidebar(){const items=[['overview','Overview'],['members','Member Database'],['ib','Sub-IB Network'],['performance','Trading Performance'],['profile','Bio & Referral']];return `<aside class="sidebar"><div class="sidebrand"><img src="${logo}"><div><b>SANS.FX HUB</b><div style="font-size:11px;color:#8f96a2">Demo Control Center</div></div></div><div class="menu">${items.map(i=>`<button class="${state.tab===i[0]?'active':''}" onclick="setTab('${i[0]}')">${i[1]}</button>`).join('')}<button onclick="location.hash='/'">← Kembali ke Website</button></div></aside>`}
function statsForRole(){if(state.role==='owner')return [['Total Member','1,248','+12.4%'],['Active Trader','784','+8.1%'],['Monthly Lot','2,438.5','+16.2%'],['Est. Revenue','$21,884','+14.8%']];if(state.role==='ib')return [['My Leads','96','+9'],['My Client','63','+6'],['Active Trader','41','+4'],['Monthly Lot','128.4','72% target']];return [['Monthly Return','+8.42%','↑ positif'],['Win Rate','64.2%','+3.1%'],['Net Profit','$342','bulan ini'],['Max Drawdown','-4.8%','terkontrol']];}
function overview(){return `<div class="stats">${statsForRole().map(s=>`<div class="stat"><span>${s[0]}</span><b>${s[1]}</b><small>${s[2]}</small></div>`).join('')}</div><div class="two"><div class="panel"><h3>Broker Performance</h3><table class="table"><thead><tr><th>Broker</th><th>Lot</th><th>Rate</th><th>Est. Commission</th></tr></thead><tbody><tr><td>HFM Premium/Cent</td><td>1,020.5</td><td>$8</td><td>${money(8164)}</td></tr><tr><td>HFM Pro</td><td>340.0</td><td>$4</td><td>${money(1360)}</td></tr><tr><td>Windsor</td><td>1,078.0</td><td>$12</td><td>${money(12936)}</td></tr></tbody></table></div><div class="panel"><h3>Top Sub-IB</h3><table class="table"><thead><tr><th>IB</th><th>Client</th><th>Lot</th><th>Bonus</th></tr></thead><tbody><tr><td>IB Andi</td><td>63</td><td>128.4</td><td><span class="badge b-gold">$220 Tier</span></td></tr><tr><td>IB Budi</td><td>42</td><td>81.2</td><td><span class="badge b-gold">$100 Tier</span></td></tr><tr><td>IB Raka</td><td>28</td><td>49.6</td><td><span class="badge b-red">Near Target</span></td></tr></tbody></table></div></div>`}
function members(){return `<div class="panel"><div class="dashhead"><h3>Member Database</h3><button class="btn btn-gold" onclick="alert('Demo: form tambah member akan terhubung ke database Supabase pada tahap integrasi.')">+ Tambah Member</button></div><table class="table"><thead><tr><th>Nama</th><th>Parent IB</th><th>Broker</th><th>Account</th><th>Status</th><th>Lot Bulan Ini</th></tr></thead><tbody>${demoMembers.map(m=>`<tr><td>${m.name}</td><td>${m.ib}</td><td>${m.broker}</td><td>${m.type}</td><td><span class="badge ${m.status==='Active'?'b-green':m.status==='Inactive'?'b-red':'b-gold'}">${m.status}</span></td><td>${m.lot}</td></tr>`).join('')}</tbody></table></div>`}
function ibnet(){return `<div class="stats"><div class="stat"><span>Total Sub-IB</span><b>18</b><small>+3 bulan ini</small></div><div class="stat"><span>Active Sub-IB</span><b>14</b><small>77.8%</small></div><div class="stat"><span>Network Lot</span><b>684.6</b><small>bulan ini</small></div><div class="stat"><span>Bonus Est.</span><b>$1,430</b><small>berjalan</small></div></div><div class="panel"><h3>Sub-IB Network</h3><table class="table"><thead><tr><th>Komunitas</th><th>Kode</th><th>Client</th><th>Lot</th><th>Progress Bonus</th><th>Bio Link</th></tr></thead><tbody><tr><td>Andi Gold Team</td><td>ANDI01</td><td>63</td><td>128.4</td><td>128 / 150</td><td><a style="color:#f1ce75" href="#/bio/andi">Buka</a></td></tr><tr><td>Budi Trader Club</td><td>BUDI07</td><td>42</td><td>81.2</td><td>81 / 100</td><td><a style="color:#f1ce75" href="#/bio/andi">Buka</a></td></tr></tbody></table></div>`}
function performance(){return `<div class="two"><div class="panel"><h3>Trading Performance Calculator</h3><div class="form-grid"><div class="field"><label>Starting Equity</label><input id="start" type="number" value="2000"></div><div class="field"><label>Ending Equity</label><input id="end" type="number" value="2180"></div><div class="field"><label>Deposit Tambahan</label><input id="dep" type="number" value="0"></div><div class="field"><label>Withdrawal</label><input id="wd" type="number" value="0"></div><div class="field"><label>Total Trade</label><input id="trades" type="number" value="28"></div><div class="field"><label>Winning Trade</label><input id="wins" type="number" value="18"></div></div><button class="btn btn-gold" style="margin-top:14px" onclick="calcPerf()">Hitung Performance</button><div id="perfResult" class="result"></div></div><div class="panel"><h3>Monthly Growth</h3><div style="display:grid;gap:12px"><div class="mini"><span>Mei</span><b>+4.2%</b></div><div class="mini"><span>Juni</span><b>+6.8%</b></div><div class="mini"><span>Juli</span><b>-2.1%</b></div><div class="mini"><span>Agustus</span><b>+8.4%</b></div></div></div></div>`}
function profile(){return `<div class="two"><div class="panel"><h3>Sub-IB Bio Settings</h3><div class="form-grid"><div class="field"><label>Nama Komunitas</label><input value="Andi Gold Team"></div><div class="field"><label>Kode Referral</label><input value="ANDI01"></div><div class="field"><label>WhatsApp</label><input value="+62 812-xxxx-xxxx"></div><div class="field"><label>Telegram</label><input value="https://t.me/..." ></div><div class="field"><label>Referral HFM</label><input value="https://..." ></div><div class="field"><label>Referral Windsor</label><input value="https://..." ></div></div><button class="btn btn-gold" style="margin-top:14px" onclick="alert('Demo tersimpan. Pada versi database, ini akan tersimpan per Sub-IB.')">Simpan</button></div><div class="panel"><h3>Public Bio</h3><p style="color:#9ca3af">Link unik siap dipasang di TikTok Bio.</p><div class="mini"><span>URL</span><b style="font-size:15px">sansfx.com/andi</b></div><a href="#/bio/andi" class="btn btn-dark" style="display:inline-block;margin-top:14px">Preview Bio</a></div></div>`}
function dashboard(){let body=state.tab==='overview'?overview():state.tab==='members'?members():state.tab==='ib'?ibnet():state.tab==='performance'?performance():profile();return `<div class="shell"><div class="dashboard">${sidebar()}<main class="content"><div class="dashhead"><div><div style="color:#9ca3af;font-size:12px">SANS.FX HUB</div><h2>${state.role==='owner'?'Owner / MIB Dashboard':state.role==='ib'?'Sub-IB Dashboard':'Member Dashboard'}</h2></div><div class="role-switch"><button class="${state.role==='owner'?'active':''}" onclick="setRole('owner')">Owner</button><button class="${state.role==='ib'?'active':''}" onclick="setRole('ib')">Sub-IB</button><button class="${state.role==='member'?'active':''}" onclick="setRole('member')">Member</button></div></div>${body}</main></div></div>`}
function bio(){return `<div class="bio-wrap"><div class="bio-card"><img src="${logo}"><div class="eyebrow" style="margin-top:15px">OFFICIAL SANS.FX PARTNER</div><h1>Andi Gold Team</h1><p>Trade • Learn • Grow bersama jaringan SANS.FX. Pilih akses yang Anda butuhkan di bawah ini.</p><div class="bio-links"><a class="primary" href="#/join?ref=ANDI01">Join Community</a><a href="#/join?ref=ANDI01&broker=HFM">Open Account HFM</a><a href="#/join?ref=ANDI01&broker=WINDSOR">Open Account Windsor</a><a href="https://wa.me/" target="_blank">WhatsApp</a><a href="https://t.me/" target="_blank">Telegram</a><a href="#/dashboard">Member Login / Dashboard</a></div><div class="footer">Powered by SANS.FX HUB</div></div></div>`}
function join(){const q=new URLSearchParams((location.hash.split('?')[1]||''));const ref=q.get('ref')||'SANSMAIN';const broker=q.get('broker')||'';return `<div class="bio-wrap" style="max-width:720px"><div class="bio-card" style="text-align:left"><div style="display:flex;align-items:center;gap:12px"><img src="${logo}" style="width:64px;height:64px"><div><b style="font-size:20px">Join SANS.FX</b><div style="color:#9ca3af;font-size:12px">Referral: ${ref}</div></div></div><div class="form-grid" style="margin-top:20px"><div class="field"><label>Nama Lengkap</label><input placeholder="Nama"></div><div class="field"><label>WhatsApp</label><input placeholder="08xxxx"></div><div class="field"><label>Email</label><input placeholder="email@contoh.com"></div><div class="field"><label>Broker</label><select><option ${broker==='HFM'?'selected':''}>HFM</option><option ${broker==='WINDSOR'?'selected':''}>Windsor</option><option>Belum pilih</option></select></div></div><div class="field" style="margin-top:12px"><label>Tujuan Bergabung</label><select><option>Member Community</option><option>Menjadi Sub-IB</option><option>Belajar Trading</option><option>Menggunakan Trading Tools</option></select></div><button class="btn btn-gold" style="width:100%;margin-top:16px" onclick="alert('Pendaftaran demo berhasil. Referral ${ref} akan otomatis tercatat pada database versi Supabase.')">Daftar Sekarang</button><a href="#/" class="btn btn-dark" style="display:block;text-align:center;margin-top:10px">Kembali</a></div></div>`}
function calcPerf(){const s=+document.querySelector('#start').value||0,e=+document.querySelector('#end').value||0,d=+document.querySelector('#dep').value||0,w=+document.querySelector('#wd').value||0,t=+document.querySelector('#trades').value||0,win=+document.querySelector('#wins').value||0;const pnl=e-s-d+w;const ret=s?100*pnl/s:0;const wr=t?100*win/t:0;document.querySelector('#perfResult').innerHTML=`<div class="mini"><span>Net Trading P/L</span><b>${money(pnl)}</b></div><div class="mini"><span>Return</span><b>${ret.toFixed(2)}%</b></div><div class="mini"><span>Win Rate</span><b>${wr.toFixed(2)}%</b></div>`}
window.setRole=r=>{state.role=r;state.tab=r==='member'?'performance':'overview';render()};window.setTab=t=>{state.tab=t;render()};
function render(){const r=location.hash||'#/';document.getElementById('app').innerHTML=r.startsWith('#/dashboard')?dashboard():r.startsWith('#/bio/')?bio():r.startsWith('#/join')?join():home();if(state.tab==='performance')setTimeout(()=>{if(document.querySelector('#start'))calcPerf()},0)}
window.addEventListener('hashchange',render);render();
